---
title: "pruebas"
author: "DANIEL PÉREZ"
date: "2024-06-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(Synth)
```

```{r}
df_pollution <- read_csv("df_pollution.csv")
```

```{r}
df_pollution$punto_muestreo <- as.numeric(df_pollution$punto_muestreo)
df_pollution$year <- as.numeric(df_pollution$year)
df_pollution$air_quality <- as.numeric(df_pollution$air_quality)
df_pollution$punto_muestreo_num <- as.numeric(as.factor(df_pollution$punto_muestreo))
sum(is.na(df_pollution$punto_muestreo))
```


```{r}
# Identificadores de tratamiento y control
treatment_ids <- unique(df_pollution$punto_muestreo[df_pollution$city_center == 1])
control_ids <- unique(df_pollution$punto_muestreo[df_pollution$city_center == 0])

# Preparar los datos para el paquete Synth
dataprep.out <- dataprep(
  foo = df_pollution,
  predictors = c("year"), # predictores para crear el control sintético
  predictors.op = "mean",
  dependent = "air_quality",
  unit.variable = "station_code", # usar la versión numérica de punto de muestreo
  time.variable = "year", # variable de tiempo (año)
  treatment.identifier = treatment_ids[1], # un identificador de tratamiento
  controls.identifier = control_ids, # identificadores de control
  time.optimize.ssr = 2017, # años para optimización (normalmente coincide con los años de pre-tratamiento)
  unit.names.variable = "punto_muestreo",
  time.plot = 2017:2019 # años para graficar
)

# Evaluar el impacto visualmente
path.plot(dataprep.res = dataprep_out, synth.res = synth_out)

# Evaluar el impacto numéricamente
synth.tables <- synth.tab(dataprep.res = dataprep_out, synth.res = synth_out)
print(synth.tables)

# Comparar la diferencia en el período post-tratamiento
gaps <- dataprep_out$Y1 - synth_out$Y0.synth
plot(2017:2019, gaps, type = "l", xlab = "Año", ylab = "Diferencia en Calidad del Aire", main = "Impacto de Madrid Central")
abline(v = 2019, col = "red") # marcar el año del tratamiento

```

